import java.io.*;
import java.lang.*;
import java.util.*;
import java.math.*;


class LargestDivisor {
    /**
     * For a given number n, find the largest number that divides n evenly, smaller than n
     * >>> largest_divisor(15)
     * 5
     *
     * > largestDivisor(3)
     * 1
     * > largestDivisor(7)
     * 1
     * > largestDivisor(10)
     * 5
     * > largestDivisor(100)
     * 50
     * > largestDivisor(49)
     * 7
     */
    public static int largestDivisor(int n) {
        if (n < 2) return -1;
        if (n == 2) return 2;
        long divisor = 2;
        while (true) {
            n = Math.abs((long)n);
            if (n % divisor == 0) {
                return (int) divisor;
            } else if (n < divisor) {
                return -1;
            }
            divisor++;
        }
    }

    // BEGIN KAWIGIEDIT TESTING
    // Generated by KawigiEdit
}